# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

In [127]:
import pandas as pd
orig_df = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv')
low_claim_df = orig_df.loc[(orig_df['Total Claim Amount']<1000) & (orig_df['Response']== 'Yes')]
orig_df.columns

Index(['Unnamed: 0', 'Customer', 'State', 'Customer Lifetime Value',
       'Response', 'Coverage', 'Education', 'Effective To Date',
       'EmploymentStatus', 'Gender', 'Income', 'Location Code',
       'Marital Status', 'Monthly Premium Auto', 'Months Since Last Claim',
       'Months Since Policy Inception', 'Number of Open Complaints',
       'Number of Policies', 'Policy Type', 'Policy', 'Renew Offer Type',
       'Sales Channel', 'Total Claim Amount', 'Vehicle Class', 'Vehicle Size',
       'Vehicle Type'],
      dtype='object')

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

In [128]:
orig_df500 = orig_df.loc[orig_df['Response']=='Yes']
pivot1 = orig_df500.pivot_table(index='Policy Type',columns='Gender', values=['Monthly Premium Auto', 'Customer Lifetime Value'], aggfunc='mean').round(2).stack()
pivot2 = orig_df500.pivot_table(index='Policy Type',columns='Gender', values=['Total Claim Amount'], aggfunc=['mean','sum']).style.format("{:,.2f}")
display(pivot1)
display(pivot2)
#Women with Corporate Auto policies seem to be the most profitable.Women are more profitable for Corporate and Personal Auto, but 
#this is not the case for Special Auto. However,special auto is the least number of claims paid out,so women still remain lower risk 
#from an insurance standpoint.

C:\Users\clair\AppData\Local\Temp\ipykernel_18080\3113279645.py:2: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  pivot1 = orig_df500.pivot_table(index='Policy Type',columns='Gender', values=['Monthly Premium Auto', 'Customer Lifetime Value'], aggfunc='mean').round(2).stack()

                       Customer Lifetime Value  Monthly Premium Auto
Policy Type    Gender
Corporate Auto F                       7712.63                 94.30
               M                       7944.47                 92.19
Personal Auto  F                       8339.79                 99.00
               M                       7448.38                 91.09
Special Auto   F                       7691.58                 92.31
               M                       8247.09                 86.34

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

In [46]:
policies_by_state = orig_df['State'].value_counts()
states_above_500 = policies_by_state.loc[lambda x:x>500]

State
California    3552
Oregon        2909
Arizona       1937
Nevada         993
Washington     888
Name: count, dtype: int64

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [58]:
orig_df.pivot_table(index=['Gender','Education'], values=['Customer Lifetime Value'], aggfunc=['max','min','median']).round(2)
#the difference between the max and min is quite large across gender and education, with the exception of doctorate holders, here
#the values fall across a more narrow distribution. Medians are highest for those with high school or below as their education 
#level, though there is relatively little variation across medians when compared to max values, with min falling in the middle in terms of variation.

                                                max                     min  \
                            Customer Lifetime Value Customer Lifetime Value
Gender Education
F      Bachelor                            73225.96                 1904.00
       College                             61850.19                 1898.68
       Doctor                              44856.11                 2395.57
       High School or Below                55277.45                 2144.92
       Master                              51016.07                 2417.78
M      Bachelor                            67907.27                 1898.01
       College                             61134.68                 1918.12
       Doctor                              32677.34                 2267.60
       High School or Below                83325.38                 1940.98
       Master                              50568.26                 2272.31

                                             median
                            Customer Lifetime Value
Gender Education
F      Bachelor                             5640.51
       College                              5623.61
       Doctor                               5332.46
       High School or Below                 6039.55
       Master                               5729.86
M      Bachelor                             5548.03
       College                              6005.85
       Doctor                               5577.67
       High School or Below                 6286.73
       Master                               5579.10

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

In [88]:
orig_df = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv')
state_by_month = orig_df.pivot_table(index='state',columns='month',aggfunc='size')
state_by_month

month          1     2
state
Arizona     1008   929
California  2231  1952
Nevada       551   442
Oregon      1565  1344
Washington   463   425

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

In [122]:
# orig_df.groupby(("state"),["month"]).agg('count')
# orig_df.groupby('state')['month'].agg(['count'])
state_by_month['totals']=state_by_month[1]+state_by_month[1]
top_policy_per_month_state = state_by_month.sort_values(by='totals', ascending = False )[:3]
top_policy_per_month_state = top_policy_per_month_state.loc[:,[1, 2]]

month          1     2
state
California  2231  1952
Oregon      1565  1344
Arizona     1008   929

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [125]:
orig_df.head()
orig_df.pivot_table(index='sales_channel', columns = 'response', aggfunc='size')

Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
       'response', 'coverage', 'education', 'effective_to_date',
       'employmentstatus', 'gender', 'income', 'location_code',
       'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type', 'month'],
      dtype='object')